export const profile = {
  name: "Aryan Singh",
  tagline: "Systems Engineer · Full-Stack · CS & Math @ UIUC",
  summary:
    "I build at the boundary where hardware, software, and network meet FPGA schedulers, zero-knowledge vaults, self-hosted Kubernetes, semantic search, and a memory allocator that beat glibc.",
  location: "Champaign, IL / Chicago, IL",
  email: "s.aryan0327@gmail.com",
  phone: "331-269-6519",
  socials: {
    github: "https://github.com/geneticglitch1",
    githubAlt: "https://github.com/geneticglitch",
    linkedin: "https://linkedin.com/in/aryan-singh06",
  },
  resume: "/resume.pdf",
  education: {
    school: "University of Illinois Urbana-Champaign",
    degree: "B.S. Computer Science & Mathematics",
    gpa: "3.89",
    graduation: "May 2027",
    coursework: [
      "Data Structures",
      "Algorithms Analysis",
      "Database Systems",
      "Systems Programming",
      "Computer Architecture",
      "Parallel Programming",
      "Formal Models of Computation",
    ],
  },
  experience: [
    {
      company: "University of Illinois Chicago",
      role: "Systems Engineer",
      period: "May 2025 – August 2025",
      location: "Chicago, IL",
      bullets: [
        'Solved the "scheduler\'s dilemma" where the OS consumes the very CPU cycles it is trying to manage by offloading complex resource allocation logic to a Xilinx Alveo U55C FPGA for more efficient task dispatching.',
        'Doubled system throughput (2× increase) by architecting a Host Memory Mapping interface, which eliminated the "double-copy" delay by allowing the host and FPGA to read/write from the same physical memory space.',
        "Streamlined data flow by developing a multi-threaded C++ application (Writer, Reader, and Logger threads) that continuously fed OS process requests into the hardware pipeline without stalling the CPU.",
        "Designed asynchronous FPGA logic using dual free-running HLS kernels to ingest job data and stream optimized results back to the host in real-time, ensuring zero idle time for the hardware accelerator.",
      ],
    },
  ],
  skills: {
    Languages: [
      "Java",
      "JavaScript",
      "TypeScript",
      "Python",
      "C",
      "C++",
      "Rust",
      "SQL",
      "HTML/CSS",
    ],
    Frameworks: ["Next.js", "React", "Spring Boot", "FastAPI", "Fastify", "Django"],
    Databases: ["PostgreSQL", "Redis", "MongoDB", "Supabase", "pgvector"],
    "AI / ML": [
      "Whisper",
      "TrOCR",
      "Instructor Embeddings",
      "RAG Pipelines",
      "LM Studio",
      "Actian VectorAI",
    ],
    Infrastructure: [
      "Docker",
      "K3s",
      "Proxmox",
      "OPNsense",
      "WireGuard",
      "Traefik",
      "Longhorn",
      "Fleet",
      "NGINX",
      "RabbitMQ",
      "MinIO",
      "Keycloak",
      "GitHub Actions",
      "CI/CD",
      "Jenkins",
    ],
    Tools: ["Git", "Linux", "VS Code", "IntelliJ", "Postman", "Vercel", "Cursor", "Claude Code"],
  },
} as const;

export type Profile = typeof profile;
