/**
 * The résumé pages the in-page viewer shows.
 *
 * Generated by scripts/render-resume.py from public/resume.pdf — rerun it and
 * paste the output here whenever the PDF changes. The PDF stays the source of
 * truth; these images exist so the résumé can be read inside the page on any
 * device, including the phones where a PDF in an iframe renders as one
 * unscrollable page.
 *
 * Dimensions are carried so the sheets can reserve their space before the
 * images decode, which keeps the viewer from reflowing as it opens.
 */

export interface ResumePage {
  page: number;
  w: number;
  h: number;
}

export const RESUME_PDF = "/resume.pdf";

export const RESUME_PAGES: ResumePage[] = [
  { page: 1, w: 1224, h: 1584 },
  { page: 2, w: 1224, h: 1584 },
];
